package com.werchat.api;

public enum WerchatActionStatus {
    SUCCESS,
    INVALID_ARGUMENT,
    PLAYER_OFFLINE,
    CHANNEL_NOT_FOUND,
    NO_DEFAULT_CHANNEL,
    NOT_MEMBER,
    ALREADY_MEMBER,
    BANNED_FROM_CHANNEL,
    INVALID_PASSWORD,
    CHANNEL_NOT_FOCUSABLE,
    PERMISSION_DENIED,
    CANCELLED_BY_HOOK
}
