{
  "formatVersion": "1.1",
  "component": {
    "group": "com.buuz135",
    "module": "MultipleHUD",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MultipleHUD-1.0.1.jar",
          "url": "MultipleHUD-1.0.1.jar",
          "size": 45291,
          "sha512": "4029ca5e8d29f8432f37c391015483d32b402e776f5d9f6e0ede9c3396ce582a8c98c6f2392c89156def7c7191e2ab6ae7afa67a4eb414d8ef5fbddc483001fb",
          "sha256": "f7711f95a92175028b9065af6c7981f70cf2613c7d80f1aa4026059669465e09",
          "sha1": "9001ad6106e2091bcb2378d3c92c99d155198cd3",
          "md5": "a20a803c065a9e0413bcbf1572f296d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MultipleHUD-1.0.1.jar",
          "url": "MultipleHUD-1.0.1.jar",
          "size": 45291,
          "sha512": "4029ca5e8d29f8432f37c391015483d32b402e776f5d9f6e0ede9c3396ce582a8c98c6f2392c89156def7c7191e2ab6ae7afa67a4eb414d8ef5fbddc483001fb",
          "sha256": "f7711f95a92175028b9065af6c7981f70cf2613c7d80f1aa4026059669465e09",
          "sha1": "9001ad6106e2091bcb2378d3c92c99d155198cd3",
          "md5": "a20a803c065a9e0413bcbf1572f296d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MultipleHUD-1.0.1-sources.jar",
          "url": "MultipleHUD-1.0.1-sources.jar",
          "size": 42692,
          "sha512": "b481274e7b527b58c1c873898bd8e4e5266254501289c350290f02ffc5d90e360eb64691475c9b9dbb7409bc0ef2cac05277725b21120b961a70e160ad855352",
          "sha256": "22febc4174d47cf9369fb4a150e3dda3a243a71d507c893cfc7c45c38caf52a2",
          "sha1": "4f44a5e561e407f87ee0d4272e28063a07b69c9f",
          "md5": "472b14f342508ad2eacfee306259ccad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MultipleHUD-1.0.1-javadoc.jar",
          "url": "MultipleHUD-1.0.1-javadoc.jar",
          "size": 4158717,
          "sha512": "f33a9f00bb158cc107e77692fd21c0f7fd1df18440306f1afa267317bc97a46d6ac55a4982214c2a0f8d8947938e2290a6de7eedc7d09a248dd03a5a58f03f39",
          "sha256": "185368c9bc8bd6c90952e7949771fe649ed50de93ed28866697b1cc6b35ef9d0",
          "sha1": "a1aa2ba843bf3dbed3bfb52530df92ba92b213b3",
          "md5": "dc440f4fe98cd3068de9ab61034c519f"
        }
      ]
    }
  ]
}
